/**
 * The two web2 admin keys of a deployment, held together to the rule the
 * stream uploader starts by: `ADMIN_API_URL` alone turns admin mode on, and
 * admin mode refuses to start without `ADMIN_API_TOKEN`. A save of a
 * deployment's settings and a create with stack settings that leave an address
 * and no token anywhere are refused, both keys named. A token counts wherever
 * it comes from: stored for the deployment, generated by the manager, or set
 * by the version.
 *
 * Unit test, no database and no deploy script, through the real routes and
 * services over in-memory rows. `pnpm test` in manager/.
 */
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { beforeEach, describe, it } from 'node:test';

import { Router } from 'express';

import type { SessionInfo } from '../../src/domain/auth/AuthService.js';
import { ALLOCATION_CONTRACT } from '../support/allocationContract.js';
import { makeProfile } from '../support/profileFixtures.js';
import { throwawayRoot } from '../support/throwawayRoot.js';
import { uploaderHealthStub } from '../support/uploaderHealthStub.js';

const root = throwawayRoot('admin-link-rule-');
process.env.SHLS_ROOT = root;

const { orchestratorHarness } = await import('../support/orchestratorHarness.js');
const { profileServiceHarness } = await import('../support/profileServiceHarness.js');
const { createDeploymentSettingsRouter } = await import('../../src/api/routes/deploymentSettings.js');
const { createProfilesRouter } = await import('../../src/api/routes/profiles.js');
const { DeploymentSettingsService } = await import('../../src/domain/settings/DeploymentSettingsService.js');
const { call, startRouterTestApp } = await import('../support/routerTestApp.js');

const INSTANCE_ID = '6f1c2b1e-3a4d-4c5e-9f60-7a8b9c0d1e2f';
const ADMIN_URL = 'https://admin.example.com';
const TOKEN = 'synthetic-admin-token-0123456789abcdef';
const REFUSAL =
  'ADMIN_API_URL is set and ADMIN_API_TOKEN is not, and the stream uploader refuses to start that way. Set ADMIN_API_TOKEN, or leave ADMIN_API_URL empty.';

const SAMPLE = `# === Stream Uploader ===
LOG_LEVEL=info
STAMP=

# === Admin mode ===
ADMIN_API_URL=
ADMIN_API_TOKEN=
`;

/** The version's own base `.env`, with what it sets for the two keys. */
function writeVersion(version: { url?: string; token?: string } = {}): void {
  writeFileSync(join(root, '.env.sample'), SAMPLE, 'utf8');
  writeFileSync(
    join(root, '.env'),
    `ENGINE=srs\nLOG_LEVEL=info\nADMIN_API_URL=${version.url ?? ''}\nADMIN_API_TOKEN=${version.token ?? ''}\n`,
    'utf8',
  );
  mkdirSync(join(root, 'engines', 'srs'), { recursive: true });
  writeFileSync(join(root, 'engines', 'srs', '.env.sample'), '# === SRS Media Server ===\nHLS_FRAGMENT=\n', 'utf8');
}

beforeEach(() => writeVersion());

function sessionFor(username: string): SessionInfo {
  return { user: { id: 1, username, isAdmin: false }, tokenHash: 'not-a-token', expiresAt: new Date(Date.now() + 60_000) };
}

/** A deployment's settings routes over the real service, signed in, and a save helper that names the revision it read. */
async function settingsApp(contract: { requiredSecrets?: string[] } = {}) {
  const stored = makeProfile({ name: 'stage', stamp_id: 'a'.repeat(64), instance_id: INSTANCE_ID });
  const harness = orchestratorHarness([stored]);
  await harness.versions.setContract(1, {
    ...structuredClone(ALLOCATION_CONTRACT),
    requiredSecrets: contract.requiredSecrets ?? [],
    serviceEnvKeys: { 'stream-uploader': ['ADMIN_API_TOKEN', 'ADMIN_API_URL', 'LOG_LEVEL', 'STAMP'], srs: ['SRS_SRT_PORT'] },
  });
  const service = new DeploymentSettingsService(
    harness.profiles.asRepository(),
    harness.containers.asRepository(),
    harness.orchestrator,
    harness.versions,
  );
  const outer = Router();
  const session = sessionFor('operator');
  outer.use((req, _res, next) => {
    req.authSession = session;
    req.user = session.user;
    next();
  });
  outer.use(createDeploymentSettingsRouter(service));
  const app = await startRouterTestApp(outer);
  let revision = 0;
  return {
    harness,
    close: () => app.close(),
    save: async (entries: { key: string; value: string | null }[]) => {
      const answer = await call(app, 'PUT', '/profiles/stage/settings', { expectedInstanceId: INSTANCE_ID, expectedRevision: revision, entries });
      if (answer.status === 200) revision = (answer.body as { revision: number }).revision;
      return answer;
    },
  };
}

function refusalOf(answer: { status: number; body: unknown }): string {
  assert.equal(answer.status, 400, JSON.stringify(answer.body));
  const { error, errors } = answer.body as { error: string; errors: string[] };
  assert.equal(error, 'validation_error');
  return errors.join(' ');
}

function accepted(answer: { status: number; body: unknown }): void {
  assert.equal(answer.status, 200, JSON.stringify(answer.body));
}

describe('a save of the web2 admin keys', () => {
  it('refuses an address with no token anywhere, naming both keys, and stores nothing', async () => {
    const app = await settingsApp();
    try {
      assert.equal(refusalOf(await app.save([{ key: 'ADMIN_API_URL', value: ADMIN_URL }])), REFUSAL);
      assert.deepEqual(await app.harness.profiles.stackSettingsForDeploy('stage'), {});
    } finally {
      await app.close();
    }
  });

  it('takes an address with a token saved beside it', async () => {
    const app = await settingsApp();
    try {
      accepted(await app.save([{ key: 'ADMIN_API_URL', value: ADMIN_URL }, { key: 'ADMIN_API_TOKEN', value: TOKEN }]));
      assert.deepEqual(await app.harness.profiles.stackSettingsForDeploy('stage'), { ADMIN_API_URL: ADMIN_URL, ADMIN_API_TOKEN: TOKEN });
    } finally {
      await app.close();
    }
  });

  it('takes an address alone once a token is stored', async () => {
    const app = await settingsApp();
    try {
      accepted(await app.save([{ key: 'ADMIN_API_TOKEN', value: TOKEN }]));
      accepted(await app.save([{ key: 'ADMIN_API_URL', value: ADMIN_URL }]));
    } finally {
      await app.close();
    }
  });

  it('takes an address alone when the version sets a token', async () => {
    writeVersion({ token: TOKEN });
    const app = await settingsApp();
    try {
      accepted(await app.save([{ key: 'ADMIN_API_URL', value: ADMIN_URL }]));
    } finally {
      await app.close();
    }
  });

  it('takes an address alone when the manager generates the token, which the version then leaves empty', async () => {
    const app = await settingsApp({ requiredSecrets: ['ADMIN_API_TOKEN'] });
    try {
      accepted(await app.save([{ key: 'ADMIN_API_URL', value: ADMIN_URL }]));
    } finally {
      await app.close();
    }
  });

  it('refuses a reset of the stored token that leaves the stored address with none', async () => {
    const app = await settingsApp();
    try {
      accepted(await app.save([{ key: 'ADMIN_API_URL', value: ADMIN_URL }, { key: 'ADMIN_API_TOKEN', value: TOKEN }]));
      assert.equal(refusalOf(await app.save([{ key: 'ADMIN_API_TOKEN', value: null }])), REFUSAL);
    } finally {
      await app.close();
    }
  });

  it('refuses a reset of the stored address back to the one the version sets, with no token', async () => {
    writeVersion({ url: ADMIN_URL });
    const app = await settingsApp();
    try {
      accepted(await app.save([{ key: 'ADMIN_API_URL', value: '' }]));
      assert.equal(refusalOf(await app.save([{ key: 'ADMIN_API_URL', value: null }])), REFUSAL);
    } finally {
      await app.close();
    }
  });

  it('takes an empty address with no token, which runs the uploader standalone', async () => {
    writeVersion({ url: ADMIN_URL });
    const app = await settingsApp();
    try {
      accepted(await app.save([{ key: 'ADMIN_API_URL', value: '' }]));
      assert.deepEqual(await app.harness.profiles.stackSettingsForDeploy('stage'), { ADMIN_API_URL: '' });
    } finally {
      await app.close();
    }
  });

  it('does not hold a save of other keys to it, as a save of other keys is not held to the engine rules', async () => {
    writeVersion({ url: ADMIN_URL });
    const app = await settingsApp();
    try {
      accepted(await app.save([{ key: 'LOG_LEVEL', value: 'debug' }]));
    } finally {
      await app.close();
    }
  });

  it('refuses a token under the uploader floor and an address with a password, repeating neither', async () => {
    const app = await settingsApp();
    const short = 'synthetic-short-token';
    const withPassword = 'https://operator:synthetic-password@admin.example.com';
    try {
      const refused = refusalOf(await app.save([{ key: 'ADMIN_API_URL', value: withPassword }, { key: 'ADMIN_API_TOKEN', value: short }]));
      assert.match(refused, /ADMIN_API_URL cannot carry a user name or a password\./);
      assert.match(refused, /ADMIN_API_TOKEN must be at least 32 characters\./);
      assert.doesNotMatch(refused, /synthetic-short-token|synthetic-password/);
    } finally {
      await app.close();
    }
  });
});

describe('a create with the web2 admin keys', () => {
  async function createApp() {
    const harness = profileServiceHarness();
    const app = await startRouterTestApp(createProfilesRouter(harness.service, uploaderHealthStub(), false), '/profiles');
    return {
      harness,
      close: () => app.close(),
      create: (settings: { key: string; value: string }[]) =>
        call(app, 'POST', '/profiles', { name: 'stage', kind: 'streamer', stack_settings: settings }),
    };
  }

  it('refuses an address with no token anywhere, naming both keys, and creates nothing', async () => {
    const app = await createApp();
    try {
      assert.equal(refusalOf(await app.create([{ key: 'ADMIN_API_URL', value: ADMIN_URL }])), REFUSAL);
      assert.equal(app.harness.profiles.rows.has('stage'), false);
    } finally {
      await app.close();
    }
  });

  it('takes an address with a token typed beside it', async () => {
    const app = await createApp();
    try {
      const created = await app.create([{ key: 'ADMIN_API_URL', value: ADMIN_URL }, { key: 'ADMIN_API_TOKEN', value: TOKEN }]);
      assert.equal(created.status, 202, JSON.stringify(created.body));
    } finally {
      await app.close();
    }
  });

  it('takes an address alone when the version sets a token', async () => {
    writeVersion({ token: TOKEN });
    const app = await createApp();
    try {
      const created = await app.create([{ key: 'ADMIN_API_URL', value: ADMIN_URL }]);
      assert.equal(created.status, 202, JSON.stringify(created.body));
    } finally {
      await app.close();
    }
  });

  it('takes an empty address, which runs the new uploader standalone whatever the version sets', async () => {
    writeVersion({ url: ADMIN_URL });
    const app = await createApp();
    try {
      const created = await app.create([{ key: 'ADMIN_API_URL', value: '' }]);
      assert.equal(created.status, 202, JSON.stringify(created.body));
      assert.deepEqual(await app.harness.profiles.stackSettingsForDeploy('stage'), { ADMIN_API_URL: '' });
    } finally {
      await app.close();
    }
  });
});
