import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { chmod, lstat, mkdir, mkdtemp, readFile, rm, symlink, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, beforeEach, test } from 'node:test';

import { BUILD_COMPLETE_MARKER, BUILD_MANIFEST_FILE } from '../../src/domain/versions/buildManifest.js';
import { copyBundledArtifact, verifyBundledArtifact } from '../../src/domain/versions/bundledArtifactFiles.js';
import { bundledArtifactMetadata } from '../../src/domain/versions/bundledArtifactMetadata.js';
import { BUNDLED_PACKAGE_MANIFEST, verifyBundledPackage } from '../../src/domain/versions/bundledShipmentPackage.js';
import { inventoryOwnedTree, sha256 } from '../../src/domain/versions/ownedTreeInventory.js';
import { bundledArtifactFixture } from '../support/bundledArtifactFixture.js';

let root: string;
beforeEach(async () => { root = await mkdtemp(join(tmpdir(), 't04b-artifact-files-')); });
afterEach(async () => { await rm(root, { recursive: true, force: true }); });

test('copies the exact sealed input pair and generated bytes into a complete fully digested artifact', async () => {
  const { sealed, record } = await bundledArtifactFixture(root);
  const output = join(root, 'candidate');
  const result = await copyBundledArtifact(sealed, output, record);
  const verified = await verifyBundledArtifact(output, { ...record, artifactDigest: result.digest, candidateContract: result.contract });
  assert.equal(verified.digest, result.digest);
  assert.equal(await readFile(join(output, BUILD_MANIFEST_FILE), 'utf8'), record.candidateMetadata!.manifestBytes);
  assert.equal(await readFile(join(output, BUILD_COMPLETE_MARKER), 'utf8'), '');
  assert.equal((await lstat(join(output, 'deploy/scripts/deploy.sh'))).mode & 0o777, 0o755);
  assert.equal((await lstat(join(output, 'entry'))).isSymbolicLink(), true);
  await assert.rejects(lstat(join(output, 'engines/new/.env')), { code: 'ENOENT' });
  const inventory = await inventoryOwnedTree(output);
  assert.equal(result.digest, sha256(JSON.stringify({ format: 1, rootMode: inventory.rootMode, entries: inventory.entries })));
  for (const file of [BUNDLED_PACKAGE_MANIFEST, BUILD_MANIFEST_FILE, BUILD_COMPLETE_MARKER]) assert.ok(inventory.entries.some(entry => entry.path === file));
  await verifyBundledPackage(sealed.root, sealed.identity);
  await assert.rejects(verifyBundledPackage(output, sealed.identity), /inventory/);
});

const mutations: Record<string, (path: string) => Promise<unknown>> = {
  content: path => writeFile(join(path, 'deploy/scripts/deploy.sh'), 'changed'),
  mode: path => chmod(join(path, 'deploy/scripts/deploy.sh'), 0o644),
  root_mode: path => chmod(path, 0o700),
  added: path => writeFile(join(path, 'unexpected'), 'extra'),
  removed: path => rm(join(path, 'deploy/scripts/deploy.sh')),
  type: async path => { await rm(join(path, 'deploy/scripts/deploy.sh')); await mkdir(join(path, 'deploy/scripts/deploy.sh')); },
  manifest_bytes: path => writeFile(join(path, BUILD_MANIFEST_FILE), '{}\n'),
  complete_bytes: path => writeFile(join(path, BUILD_COMPLETE_MARKER), 'changed'),
  complete_mode: path => chmod(join(path, BUILD_COMPLETE_MARKER), 0o600),
  package_manifest_mode: path => chmod(join(path, BUNDLED_PACKAGE_MANIFEST), 0o644),
  absent_input: async path => { await mkdir(join(path, 'engines/new'), { recursive: true }); await writeFile(join(path, 'engines/new/.env'), 'unexpected'); },
  missing_input: path => rm(join(path, '.env')),
  escaping_link: async path => { await rm(join(path, 'entry')); await symlink('../outside', join(path, 'entry')); },
};
for (const [name, mutate] of Object.entries(mutations)) {
  test(`rejects changed final ${name}`, async () => {
    const { sealed, record } = await bundledArtifactFixture(root);
    const output = join(root, 'candidate');
    const result = await copyBundledArtifact(sealed, output, record);
    await mutate(output);
    await assert.rejects(verifyBundledArtifact(output, { ...record, artifactDigest: result.digest, candidateContract: result.contract }));
  });
}

for (const reservedFile of [BUILD_MANIFEST_FILE, BUILD_COMPLETE_MARKER]) {
  test(`refuses a sealed package containing reserved ${reservedFile}`, async () => {
    const { sealed, record } = await bundledArtifactFixture(root, { reservedFile });
    await assert.rejects(copyBundledArtifact(sealed, join(root, 'candidate'), record), /reserved|generated/i);
  });
}

test('refuses candidate input metadata that omits or changes any captured input', async () => {
  const { sealed, record } = await bundledArtifactFixture(root);
  for (const inputHashes of [{}, { ...record.candidateManifest!.inputHashes, '.env': '0'.repeat(64) }]) {
    const manifest = { ...record.candidateManifest!, inputHashes };
    await assert.rejects(copyBundledArtifact(sealed, join(root, 'candidate'), { ...record, candidateManifest: manifest, candidateMetadata: bundledArtifactMetadata(manifest) }), /input/i);
  }
});

test('rechecks a previously verified token before reading changed package bytes', async () => {
  const { sealed, record } = await bundledArtifactFixture(root);
  await writeFile(join(sealed.root, '.env'), 'changed');
  await assert.rejects(copyBundledArtifact(sealed, join(root, 'candidate'), record), /package|input|inventory/i);
  await assert.rejects(lstat(join(root, 'candidate')), { code: 'ENOENT' });
});

test('refuses source mutation during copying and removes only its owned incomplete destination', async () => {
  const { sealed, record } = await bundledArtifactFixture(root);
  await writeFile(join(root, 'sentinel'), 'keep');
  let changed = false;
  await assert.rejects(copyBundledArtifact(sealed, join(root, 'candidate'), record, { onProgress: async () => {
    if (!changed) { changed = true; await writeFile(join(sealed.root, '.env'), 'changed'); }
  } }), /changed|package|inventory/i);
  await assert.rejects(lstat(join(root, 'candidate')), { code: 'ENOENT' });
  assert.equal(await readFile(join(root, 'sentinel'), 'utf8'), 'keep');
});

for (const occupied of ['empty', 'nonempty', 'file'] as const) {
  test(`never replaces an existing ${occupied} destination`, async () => {
    const { sealed, record } = await bundledArtifactFixture(root);
    const output = join(root, 'candidate');
    if (occupied === 'file') await writeFile(output, 'keep');
    else { await mkdir(output); if (occupied === 'nonempty') await writeFile(join(output, 'sentinel'), 'keep'); }
    const before = await lstat(output);
    await assert.rejects(copyBundledArtifact(sealed, output, record));
    assert.equal((await lstat(output)).ino, before.ino);
    if (occupied !== 'empty') assert.equal(await readFile(occupied === 'file' ? output : join(output, 'sentinel'), 'utf8'), 'keep');
  });
}

test('verifies reused bytes against a recorded final digest while retaining the original package identity', async () => {
  const { sealed, record } = await bundledArtifactFixture(root);
  const output = join(root, 'candidate');
  const result = await copyBundledArtifact(sealed, output, record);
  const reuse = { ...record, shipmentId: randomUUID(), packageDigest: 'f'.repeat(64), candidateKind: 'reuse' as const, artifactDigest: result.digest, candidateContract: result.contract };
  assert.equal((await verifyBundledArtifact(output, reuse)).digest, result.digest);
  await assert.rejects(verifyBundledArtifact(output, { ...reuse, artifactDigest: '0'.repeat(64) }), /digest/i);
  await assert.rejects(verifyBundledArtifact(output, { ...reuse, artifactDigest: null }), /digest|reuse/i);
});
