/**
 * The uploader's web2 admin token of its own: generated by a deploy for a deployment whose uploader is given the
 * address of the manager's web2 admin link, kept from then on, written into its env file, and never where it would
 * reach another admin. docs/features/web2-admin-link.md, "A token of its own".
 *
 * Unit test, no database and no Docker. `pnpm test` in manager/.
 */
import assert from 'node:assert/strict';
import { mkdirSync, mkdtempSync, readFileSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, it } from 'node:test';

import { ADMIN_API_TOKEN_KEY, ADMIN_API_URL_KEY, type StackContract } from '@streaming-infra-manager/common';

import type { ProfileKind } from '../../src/types/index.js';
import { InMemoryManagerAdminLink } from '../support/InMemoryManagerAdminLink.js';
import { makeProfile } from '../support/profileFixtures.js';
import { ALLOCATION_CONTRACT } from '../support/allocationContract.js';

const root = join(mkdtempSync(join(tmpdir(), 'own-admin-token-')), 'stack');
mkdirSync(join(root, 'engines', 'srs'), { recursive: true });
process.env.SHLS_ROOT = root;

const { orchestratorHarness, untilRunning } = await import('../support/orchestratorHarness.js');
const { ownAdminTokenFor, runsStreamUploader, takesOwnAdminToken } =
  await import('../../src/domain/adminLink/ownAdminToken.js');

const ADMIN_URL = 'https://admin.example.org';
const LINK_TOKEN = 'synthetic-link-admin-token-0123456789abcdef';
const COPIED_TOKEN = 'synthetic-copied-admin-token-fedcba9876543210';
const STAMP = 'a'.repeat(64);

const CONTRACT: StackContract = { ...structuredClone(ALLOCATION_CONTRACT), requiredSecrets: [] };

function writeVersion(baseEnv = 'ENGINE=srs\nLOG_LEVEL=info\nADMIN_API_URL=\nADMIN_API_TOKEN=\n'): void {
  writeFileSync(join(root, '.env'), baseEnv, 'utf8');
  writeFileSync(join(root, '.env.sample'), 'LOG_LEVEL=debug\nADMIN_API_URL=\nADMIN_API_TOKEN=\n', 'utf8');
  writeFileSync(join(root, 'engines', 'srs', '.env'), 'SRT_LATENCY=\n', 'utf8');
}

interface Setup {
  kind?: ProfileKind;
  components?: string[] | null;
  /** What the deployment stores for its settings. */
  settings?: Record<string, string>;
  link?: { url: string | null; token: string | null } | null;
  baseEnv?: string;
}

async function harnessFor(setup: Setup = {}) {
  writeVersion(setup.baseEnv);
  const stored = makeProfile({
    name: 'stage',
    port_slot: 3,
    stamp_id: STAMP,
    kind: setup.kind ?? 'streamer',
    components: setup.components ?? null,
  });
  const harness = orchestratorHarness([stored]);
  await harness.versions.setContract(1, structuredClone(CONTRACT));
  harness.profiles.stackSettings.set('stage', setup.settings ?? { [ADMIN_API_URL_KEY]: ADMIN_URL });
  if (setup.link !== null) {
    const link = new InMemoryManagerAdminLink();
    link.url = setup.link?.url === undefined ? ADMIN_URL : setup.link.url;
    link.token = setup.link?.token === undefined ? LINK_TOKEN : setup.link.token;
    harness.orchestrator.setManagerAdminLink(link);
  }
  return harness;
}

async function deploy(harness: Awaited<ReturnType<typeof harnessFor>>): Promise<void> {
  const index = harness.runner.runs.length;
  await harness.orchestrator.startDeploy(harness.profiles.rows.get('stage')!, undefined);
  harness.runner.finish(index);
  await untilRunning(harness.profiles, 'stage');
}

/** The value the deployment's env file gives a key, or undefined when it writes no line for it. */
function envFileValue(key: string): string | undefined {
  const lines = readFileSync(join(root, '.env.stage'), 'utf8')
    .split('\n')
    .filter((entry) => entry.startsWith(`${key}=`));
  return lines.at(-1)?.slice(key.length + 1);
}

describe("the rule for a token of the deployment's own", () => {
  it("is the manager's link address, for a deployment that runs a stream uploader and a link with a token", () => {
    const link = { url: ADMIN_URL, tokenStored: true };
    assert.equal(ownAdminTokenFor(link, { kind: 'streamer' }), ADMIN_URL);
    assert.equal(ownAdminTokenFor(link, { kind: 'abr-uploader' }), ADMIN_URL);
    assert.equal(ownAdminTokenFor(link, { kind: 'viewer' }), null);
    assert.equal(ownAdminTokenFor({ url: ADMIN_URL, tokenStored: false }, { kind: 'streamer' }), null);
    assert.equal(ownAdminTokenFor({ url: null, tokenStored: false }, { kind: 'streamer' }), null);
    assert.equal(ownAdminTokenFor(null, { kind: 'streamer' }), null);
    assert.equal(runsStreamUploader({ kind: 'custom', components: ['srs', 'stream-uploader'] }), true);
  });

  it("goes to an address on the link's origin alone", () => {
    assert.equal(takesOwnAdminToken(`${ADMIN_URL}/v2`, ADMIN_URL), true);
    assert.equal(takesOwnAdminToken('https://elsewhere.example.org', ADMIN_URL), false);
    assert.equal(takesOwnAdminToken('http://admin.example.org', ADMIN_URL), false);
    assert.equal(takesOwnAdminToken('', ADMIN_URL), false);
    assert.equal(takesOwnAdminToken(ADMIN_URL, null), false);
  });
});

describe("a deploy of an uploader linked to the manager's web2 admin", () => {
  it('generates a token of its own, 64 hex characters, keeps it and writes it into the env file', async () => {
    const harness = await harnessFor();
    await deploy(harness);

    const generated = harness.profiles.secrets.get('stage')?.[ADMIN_API_TOKEN_KEY];
    assert.match(generated ?? '', /^[0-9a-f]{64}$/);
    assert.notEqual(generated, LINK_TOKEN);
    assert.equal(envFileValue(ADMIN_API_TOKEN_KEY), generated);

    const next = await harness.orchestrator.nextEnvFor(harness.profiles.rows.get('stage')!);
    assert.equal(next.env[ADMIN_API_TOKEN_KEY], generated, 'the stage record hashes the one the uploader is given');
    assert.ok(next.generatedKeys.includes(ADMIN_API_TOKEN_KEY));
  });

  it('never replaces the one it stores on a later deploy', async () => {
    const harness = await harnessFor();
    await deploy(harness);
    const first = harness.profiles.secrets.get('stage')?.[ADMIN_API_TOKEN_KEY];

    await deploy(harness);

    assert.equal(harness.profiles.secrets.get('stage')?.[ADMIN_API_TOKEN_KEY], first);
    assert.equal(envFileValue(ADMIN_API_TOKEN_KEY), first);
  });

  it('generates none for a deployment that stores a token, which is written in its place', async () => {
    const harness = await harnessFor({
      settings: { [ADMIN_API_URL_KEY]: ADMIN_URL, [ADMIN_API_TOKEN_KEY]: COPIED_TOKEN },
    });
    await deploy(harness);

    assert.equal(harness.profiles.secrets.get('stage')?.[ADMIN_API_TOKEN_KEY], undefined);
    assert.equal(envFileValue(ADMIN_API_TOKEN_KEY), COPIED_TOKEN);
  });

  it('generates none before a version whose settings answer the token', async () => {
    const harness = await harnessFor({ baseEnv: `ENGINE=srs\nADMIN_API_URL=\nADMIN_API_TOKEN=${COPIED_TOKEN}\n` });
    await deploy(harness);

    assert.equal(harness.profiles.secrets.get('stage')?.[ADMIN_API_TOKEN_KEY], undefined);
  });
});

describe('a deploy that gives no token of its own', () => {
  for (const [name, setup] of [
    ['an address on another origin', { settings: { [ADMIN_API_URL_KEY]: 'https://elsewhere.example.org' } }],
    ['no address', { settings: { [ADMIN_API_URL_KEY]: '' } }],
    ['a link with no token to register it with', { link: { url: ADMIN_URL, token: null } }],
    ['no link', { link: { url: null, token: null } }],
    ['a manager that was given no link to read', { link: null }],
    ['a deployment that runs no stream uploader', { kind: 'viewer' }],
  ] as const) {
    it(`generates none for ${name}`, async () => {
      const harness = await harnessFor(setup as Setup);
      await deploy(harness);
      assert.equal(harness.profiles.secrets.get('stage')?.[ADMIN_API_TOKEN_KEY], undefined);
    });
  }

  it('does not write a token it generated once the address moves to another admin', async () => {
    const harness = await harnessFor();
    await deploy(harness);
    const generated = harness.profiles.secrets.get('stage')?.[ADMIN_API_TOKEN_KEY];
    assert.ok(generated);

    harness.profiles.stackSettings.set('stage', { [ADMIN_API_URL_KEY]: 'https://elsewhere.example.org' });
    await deploy(harness);

    assert.notEqual(envFileValue(ADMIN_API_TOKEN_KEY), generated);
    const next = await harness.orchestrator.nextEnvFor(harness.profiles.rows.get('stage')!);
    assert.notEqual(next.env[ADMIN_API_TOKEN_KEY], generated);
  });
});
