/**
 * What the deployment settings editor says: the drift banner, what Apply did,
 * the default beside a value, what a control-owned or secret key says, and
 * why a save or an apply was refused.
 *
 * Unit test, no browser. `pnpm test` in frontend/.
 *
 * Every sentence here reaches an operator who may not know the codebase, so
 * each one names the keys and the services rather than counting them, and
 * none carries an em-dash or a semicolon.
 */
import assert from 'node:assert/strict';
import { describe, it } from 'node:test';

import {
  type DeploymentSettingEntry,
  type DeploymentSettingsCatalog,
  SETTING_OWNER_LABELS,
  type SettingOwner,
} from '@streaming-infra-manager/common';

import {
  OWNED_STORED_NOTE,
  REMOVAL_PENDING_NOTE,
  RESET_PENDING_NOTE,
  UNDECLARED_NOTE,
  UNRECORDED_NOTE,
  UNSAVED_NOT_APPLIED_NOTE,
  WHAT_SAVING_DOES,
  appliedText,
  applyRefusalText,
  behindNote,
  defaultText,
  descriptionPreview,
  driftNotice,
  fieldHint,
  loadFailureOf,
  noMatchText,
  ownedValueText,
  ownerSentence,
  recreatesText,
  saveNote,
  saveRefusalOf,
  savedText,
  secretNote,
  sectionSummary,
  startedBeforeRecords,
  wordList,
} from './settingsText';

function entry(overrides: Partial<DeploymentSettingEntry> & { key: string }): DeploymentSettingEntry {
  return {
    section: '',
    description: '',
    declared: true,
    secret: false,
    sampleValue: null,
    versionSet: true,
    versionValue: null,
    stored: false,
    storedValue: null,
    value: null,
    source: 'version',
    owner: null,
    field: null,
    services: null,
    running: 'same',
    ...overrides,
  };
}

function catalogWith(drift: DeploymentSettingsCatalog['drift'], running: boolean): DeploymentSettingsCatalog {
  return { instanceId: 'i', revision: 1, buildId: null, entries: [], drift, running };
}

describe('wordList', () => {
  it('names one, two or many things the way a sentence does', () => {
    assert.equal(wordList([]), '');
    assert.equal(wordList(['srs']), 'srs');
    assert.equal(wordList(['srs', 'stream-uploader']), 'srs and stream-uploader');
    assert.equal(wordList(['srs', 'stream-uploader', 'bee-uploader']), 'srs, stream-uploader and bee-uploader');
  });
});

describe('recreatesText', () => {
  it('names the services a change recreates', () => {
    assert.equal(recreatesText(['stream-uploader']), 'recreates stream-uploader');
    assert.equal(recreatesText(['srs', 'stream-uploader']), 'recreates srs and stream-uploader');
  });

  it('says full redeploy for a key no container reads, which only the deploy scripts do', () => {
    assert.equal(recreatesText(null), 'full redeploy');
    assert.equal(recreatesText([]), 'full redeploy');
  });
});

describe('ownerSentence', () => {
  it('names the control that decides the key, in the shared words', () => {
    assert.equal(ownerSentence('stamp'), "Decided by the deployment's postage stamp. It cannot be set here.");
  });

  it('reads as a sentence for every control', () => {
    for (const owner of Object.keys(SETTING_OWNER_LABELS) as SettingOwner[]) {
      assert.match(ownerSentence(owner), /^Decided by .+\. It cannot be set here\.$/);
    }
  });
});

describe('ownedValueText', () => {
  it('shows the value a control decided, and says so where there is none to show', () => {
    assert.equal(ownedValueText(entry({ key: 'STAMP', value: 'ab12' })), 'ab12');
    assert.equal(ownedValueText(entry({ key: 'BEE_PUBLISHERS', value: '' })), 'empty');
    assert.equal(ownedValueText(entry({ key: 'BEE_URL', value: null })), 'not set');
    assert.equal(ownedValueText(entry({ key: 'STREAM_KEY', secret: true })), 'hidden');
  });
});

describe('defaultText', () => {
  it("gives the version's value as the default", () => {
    assert.equal(defaultText(entry({ key: 'LOG_LEVEL', versionValue: 'info' })), 'Default: info');
    assert.equal(defaultText(entry({ key: 'ADMIN_API_URL', versionValue: '' })), 'Default: empty');
  });

  it("says the stack decides a key the version leaves unset", () => {
    assert.equal(
      defaultText(entry({ key: 'BEE_REQUEST_TIMEOUT_MS', versionSet: false })),
      "Default: not set, so the stack's own default applies",
    );
  });

  it("never shows a secret's default, only where it comes from", () => {
    assert.equal(
      defaultText(entry({ key: 'API_AUTH_TOKEN', secret: true, versionSet: false, source: 'generated' })),
      'Default: generated by the manager for this deployment',
    );
    assert.equal(defaultText(entry({ key: 'ADMIN_API_TOKEN', secret: true })), 'Default: set by the version, never shown');
    assert.equal(defaultText(entry({ key: 'OME_ADMISSION_SECRET', secret: true, versionSet: false })), 'Default: not set by the version');
  });
});

describe('secretNote', () => {
  it('says a secret is stored without ever showing it', () => {
    assert.equal(
      secretNote(entry({ key: 'ADMIN_API_TOKEN', secret: true, stored: true, source: 'deployment' })),
      'A value is stored for this deployment. It is never shown. Type a new one to replace it.',
    );
  });

  it('says where the value comes from while the deployment stores none', () => {
    assert.match(secretNote(entry({ key: 'API_AUTH_TOKEN', secret: true, source: 'generated' })), /^The manager generated a value/);
    assert.match(secretNote(entry({ key: 'ADMIN_API_TOKEN', secret: true })), /^The version sets a value/);
    assert.match(secretNote(entry({ key: 'OME_ADMISSION_SECRET', secret: true, versionSet: false, source: 'unset' })), /^Not set\./);
  });
});

describe('driftNotice', () => {
  it('says nothing while nothing is behind', () => {
    assert.equal(driftNotice(catalogWith({ keys: [], services: [], fullRedeploy: false }, true)), null);
  });

  it('names the keys the running containers are behind on and what Apply recreates', () => {
    const notice = driftNotice(catalogWith({ keys: ['LOG_LEVEL'], services: ['stream-uploader'], fullRedeploy: false }, true));

    assert.deepEqual(notice, {
      text: '1 setting is behind the running containers: LOG_LEVEL. Apply recreates stream-uploader.',
      offersApply: true,
    });
  });

  it('says Apply redeploys everything when a key reaches the deploy scripts alone', () => {
    const notice = driftNotice(
      catalogWith({ keys: ['LOG_LEVEL', 'BEE_UPLOADER_FULL_NODE'], services: ['stream-uploader'], fullRedeploy: true }, true),
    );

    assert.equal(
      notice?.text,
      '2 settings are behind the running containers: LOG_LEVEL and BEE_UPLOADER_FULL_NODE. Apply redeploys every service of this deployment.',
    );
  });

  it('offers no Apply to a stopped deployment, whose Start uses the saved settings', () => {
    const notice = driftNotice(catalogWith({ keys: ['LOG_LEVEL', 'MAX_QUEUE_SIZE'], services: ['stream-uploader'], fullRedeploy: false }, false));

    assert.deepEqual(notice, { text: 'Start will use 2 changed settings: LOG_LEVEL and MAX_QUEUE_SIZE.', offersApply: false });
  });

  it('counts one changed setting in the singular for a stopped deployment', () => {
    const notice = driftNotice(catalogWith({ keys: ['LOG_LEVEL'], services: [], fullRedeploy: false }, false));

    assert.equal(notice?.text, 'Start will use 1 changed setting: LOG_LEVEL.');
  });
});

describe('appliedText', () => {
  it('says what Apply recreated', () => {
    assert.equal(appliedText({ recreated: ['stream-uploader'] }), 'Applied. Recreating stream-uploader with the saved settings.');
    assert.equal(appliedText({ recreated: 'all' }), 'Applied. Every service of this deployment is being redeployed with the saved settings.');
    assert.equal(appliedText({ recreated: [] }), 'Nothing was behind, so nothing was recreated.');
  });
});

describe('saveNote', () => {
  it('says what the save would send', () => {
    assert.equal(saveNote(0, []), 'Nothing changed yet');
    assert.equal(saveNote(1, []), '1 setting changed');
    assert.equal(saveNote(3, []), '3 settings changed');
  });

  it('names the values that stop the save first', () => {
    assert.equal(saveNote(2, ['MAX_QUEUE_SIZE']), 'One value cannot be saved as written: MAX_QUEUE_SIZE');
    assert.equal(saveNote(2, ['MAX_QUEUE_SIZE', 'LOG_LEVEL']), '2 values cannot be saved as written: MAX_QUEUE_SIZE and LOG_LEVEL');
  });
});

describe('descriptionPreview', () => {
  it('keeps a short description whole', () => {
    assert.deepEqual(descriptionPreview('The log level.'), { text: 'The log level.', cut: false });
  });

  it('cuts a long one at a word, and says it did', () => {
    const long = `${'word '.repeat(80)}end`;
    const preview = descriptionPreview(long, 40);

    assert.equal(preview.cut, true);
    assert.ok(preview.text.length <= 41, preview.text);
    assert.match(preview.text, /word…$/);
  });
});

describe('fieldHint', () => {
  it('says what a number field takes, bounds included', () => {
    assert.equal(fieldHint({ kind: 'integer', min: 1, max: 600000 }), 'A whole number from 1 to 600000.');
    assert.equal(fieldHint({ kind: 'integer', min: 1 }), 'A whole number, 1 or more.');
    assert.equal(fieldHint({ kind: 'number', min: 0, max: 1 }), 'A number from 0 to 1. Use a period for decimals.');
    assert.equal(fieldHint({ kind: 'number' }), 'A number. Use a period for decimals.');
  });

  it('says nothing for a field whose control already shows what it takes', () => {
    assert.equal(fieldHint({ kind: 'choice', choices: ['a'] }), null);
    assert.equal(fieldHint({ kind: 'boolean' }), null);
    assert.equal(fieldHint(null), null);
  });
});

describe('refusals', () => {
  it('reads the list again after a save that lost a race, and says to make the change again', () => {
    const refusal = saveRefusalOf('deployment_settings_changed', 'manager words');

    assert.equal(refusal.reload, true);
    assert.match(refusal.message, /changed elsewhere/);
    assert.match(refusal.message, /Make your change again\./);
  });

  it("shows the manager's own sentences for any other refusal", () => {
    assert.deepEqual(saveRefusalOf('validation_error', 'MAX_QUEUE_SIZE must be at least 1. Got 0.'), {
      message: 'MAX_QUEUE_SIZE must be at least 1. Got 0.',
      reload: false,
    });
  });

  it('says in words that a busy deployment cannot be applied to yet', () => {
    assert.equal(applyRefusalText('profile_busy', 'profile_busy'), 'The deployment is deploying or stopping right now. Apply once it has finished.');
    assert.equal(applyRefusalText('profile_stopped', 'This deployment is stopped.'), 'This deployment is stopped.');
  });

  it('tells a version with no build yet apart from a list that could not be read', () => {
    assert.deepEqual(loadFailureOf('settings_not_ready', 'v9 has no settings yet. It has no build.'), {
      message: 'v9 has no settings yet. It has no build.',
      severity: 'info',
    });
    assert.deepEqual(loadFailureOf(null, 'request failed (502)'), {
      message: 'Could not read the settings. request failed (502)',
      severity: 'warning',
    });
  });
});

describe('sectionSummary', () => {
  it('counts the keys of a folded section and what waits inside it', () => {
    assert.equal(sectionSummary(1, { unsaved: 0, refused: 0, behind: 0 }), '1 setting');
    assert.equal(sectionSummary(12, { unsaved: 0, refused: 0, behind: 0 }), '12 settings');
    assert.equal(
      sectionSummary(12, { unsaved: 2, refused: 1, behind: 1 }),
      '12 settings, 2 unsaved, 1 cannot be saved, 1 not applied',
    );
  });
});

describe('what a save and the list say about the running containers', () => {
  it('says a save restarts nothing, and what the saved values wait for', () => {
    assert.equal(savedText(true), 'Saved. The running containers keep their old values until you apply them.');
    assert.equal(savedText(false), 'Saved. The next start uses them.');
  });

  it('tells containers started before any record apart from a key no running container reads', () => {
    const unknown = (key: string) => entry({ key, running: 'unknown' });
    const listOf = (entries: DeploymentSettingEntry[], running = true): DeploymentSettingsCatalog => ({
      ...catalogWith({ keys: [], services: [], fullRedeploy: false }, running),
      entries,
    });

    assert.equal(startedBeforeRecords(listOf([unknown('LOG_LEVEL'), unknown('BEE_GATEWAY_CACHE_RETRIEVAL')])), true);
    assert.equal(
      startedBeforeRecords(listOf([entry({ key: 'LOG_LEVEL', running: 'same' }), unknown('BEE_GATEWAY_CACHE_RETRIEVAL')])),
      false,
      'a gateway key on a deployment with no gateway is unknown on its own',
    );
    assert.equal(startedBeforeRecords(listOf([unknown('LOG_LEVEL')], false)), false, 'a stopped deployment has nothing running to compare');
    assert.equal(startedBeforeRecords(listOf([])), false);
  });

  it('says a search found nothing, naming what was searched for', () => {
    assert.equal(noMatchText('  gates '), 'No setting matches "gates".');
  });
});

describe('the words themselves', () => {
  it('carry no em-dash and no semicolon', () => {
    const sentences = [
      ...Object.keys(SETTING_OWNER_LABELS).map((owner) => ownerSentence(owner as SettingOwner)),
      driftNotice(catalogWith({ keys: ['A', 'B'], services: ['srs'], fullRedeploy: true }, true))?.text ?? '',
      driftNotice(catalogWith({ keys: ['A'], services: ['srs'], fullRedeploy: false }, false))?.text ?? '',
      appliedText({ recreated: 'all' }),
      appliedText({ recreated: [] }),
      saveRefusalOf('deployment_settings_changed', '').message,
      applyRefusalText('profile_busy', ''),
      secretNote(entry({ key: 'K', secret: true, stored: true })),
      secretNote(entry({ key: 'K', secret: true, source: 'generated' })),
      defaultText(entry({ key: 'K', versionSet: false })),
      savedText(true),
      savedText(false),
      UNRECORDED_NOTE,
      WHAT_SAVING_DOES,
      UNSAVED_NOT_APPLIED_NOTE,
      OWNED_STORED_NOTE,
      UNDECLARED_NOTE,
      RESET_PENDING_NOTE,
      REMOVAL_PENDING_NOTE,
      behindNote(true),
      behindNote(false),
    ];
    for (const sentence of sentences) {
      assert.equal(/[—;]/.test(sentence), false, sentence);
    }
  });
});
