import {
  type DeploymentSettingEntry,
  type DeploymentSettingsApplied,
  type DeploymentSettingsCatalog,
  type EngineDefaultSource,
  type EngineSettingField,
  isNotReadOwner,
  SETTING_OWNER_LABELS,
  type SettingOwner,
  type StackSettingField,
} from '@streaming-infra-manager/common';

/**
 * Everything the deployment settings editor says in words. The editor reads
 * these rather than writing sentences inline, so each one is pinned by a test
 * and a change of wording is a change here.
 */

/**
 * Whom an edit is for: a deployment that exists, whose values a save stores,
 * or one the new-deployment wizard has not created yet, whose values its
 * create sends.
 */
export type SettingsEditTarget = 'deployment' | 'new-deployment';

/** The line over the list: what a save does, and what it does not. */
export const WHAT_SAVING_DOES =
  "Every key this deployment's version declares and every engine setting it reads, each with its default beside it. Saving stores the values and restarts nothing. The running containers keep theirs until you apply them.";

/** Said beside Apply while the draft holds changes, which Apply does not carry. */
export const UNSAVED_NOT_APPLIED_NOTE = 'Changes you have not saved are not part of it.';

/** Things named the way a sentence names them: "a", "a and b", "a, b and c". */
export function wordList(items: readonly string[]): string {
  if (items.length <= 1) return items.join('');
  return `${items.slice(0, -1).join(', ')} and ${items.at(-1)}`;
}

/**
 * What applying a change to a key recreates. A key no container's compose
 * block reads reaches the deploy scripts alone, and those decide how every
 * container starts, so its change is a full redeploy.
 */
export function recreatesText(services: readonly string[] | null): string {
  if (services === null || services.length === 0) return 'full redeploy';
  return `recreates ${wordList(services)}`;
}

function capitalized(text: string): string {
  return text.charAt(0).toUpperCase() + text.slice(1);
}

/**
 * Why a key has no field of its own here: one of the deployment's controls
 * decides it, or it is an engine setting this deployment does not read.
 */
export function ownerSentence(owner: SettingOwner): string {
  if (isNotReadOwner(owner)) return `${capitalized(SETTING_OWNER_LABELS[owner])}, so it cannot be set here.`;
  return `Decided by ${SETTING_OWNER_LABELS[owner]}. It cannot be set here.`;
}

/** The value a control decided, as the page shows it. A secret's is never shown. */
export function ownedValueText(entry: DeploymentSettingEntry): string {
  if (entry.secret) return 'hidden';
  if (entry.value === null) return 'not set';
  return entry.value === '' ? 'empty' : entry.value;
}

/** What a key goes back to on a reset, which is what the version sets. */
export function defaultText(entry: DeploymentSettingEntry): string {
  if (entry.secret) {
    if (entry.source === 'generated') return 'Default: generated by the manager for this deployment';
    return entry.versionSet ? 'Default: set by the version, never shown' : 'Default: not set by the version';
  }
  if (!entry.versionSet) return "Default: not set, so the stack's own default applies";
  return entry.versionValue === '' || entry.versionValue === null ? 'Default: empty' : `Default: ${entry.versionValue}`;
}

/** Where an engine setting's default comes from, as the Engine card names it. */
const ENGINE_DEFAULT_ORIGIN: Readonly<Record<EngineDefaultSource, string>> = {
  host: 'set on this host',
  stack: "the version's own",
  manager: "the manager's own",
};

/**
 * What an engine setting goes back to on a reset: what an unset one falls
 * back to on the deployment's host, in the field's unit, and where that comes
 * from, a default the manager owns named as the manager's.
 */
export function engineDefaultText(entry: DeploymentSettingEntry, field: EngineSettingField): string {
  const value = entry.versionValue ?? field.defaultValue;
  const unit = field.unit ? ` ${field.unit}` : '';
  const origin = ENGINE_DEFAULT_ORIGIN[entry.engineSetting?.defaultSource ?? 'stack'];
  return `Default: ${value}${unit}, ${origin}`;
}

/** What an engine setting's number field takes, for the line under it, or null for a list, which shows its choices. */
export function engineFieldHint(field: EngineSettingField): string | null {
  return field.kind === 'choice' ? null : fieldHint({ kind: field.kind, min: field.min, max: field.max });
}

/**
 * Said under an engine setting the config the engine runs no longer reads:
 * the deployment's own config file, or the version's template where it runs
 * none of its own.
 */
export function notInConfigNote(ownConfig: boolean): string {
  return ownConfig
    ? "The deployment's own config file no longer reads this setting, so a value here has no effect until the file reads it again."
    : "This version's config does not read this setting, so a value here has no effect on this version.";
}

/** Where a secret's value comes from, in place of the value, which is never shown. */
export function secretNote(entry: DeploymentSettingEntry, target: SettingsEditTarget = 'deployment'): string {
  if (entry.stored) return 'A value is stored for this deployment. It is never shown. Type a new one to replace it.';
  if (entry.source === 'generated' && target === 'new-deployment') {
    return 'The manager generates a value for this deployment when it first deploys. Type one to use your own instead.';
  }
  if (entry.source === 'generated') {
    return 'The manager generated a value for this deployment. Type one to use your own instead.';
  }
  if (entry.versionSet) return 'The version sets a value. Type one to use your own for this deployment.';
  return 'Not set. Type a value to set one for this deployment.';
}

/** Said under a key a control decides when the deployment still stores a value for it from before. */
export const OWNED_STORED_NOTE = 'A value stored for it here earlier is not used. Reset takes it out.';

/** Said under a key the version no longer declares, which the deployment still stores. */
export const UNDECLARED_NOTE =
  "This version no longer declares this key, but the value stored for it is still written into the deployment's env file. Reset takes it out.";

/** Said under a key whose reset is waiting for the save. */
export const RESET_PENDING_NOTE = 'Goes back to the default when you save.';

/** Said under a key whose stored value the save takes out, where the key has no default of its own here. */
export const REMOVAL_PENDING_NOTE = 'Taken out of the stored settings when you save.';

/** Said under a saved key the running containers do not have yet. */
export function behindNote(running: boolean): string {
  return running
    ? 'Saved, and the running containers still have the old value until you apply it.'
    : 'Saved. The next start uses it.';
}

export interface DriftNotice {
  text: string;
  /** Whether Apply means anything: a stopped deployment's Start uses the saved settings anyway. */
  offersApply: boolean;
}

/** The banner over the list, or null when the containers have every saved setting. */
export function driftNotice(catalog: DeploymentSettingsCatalog): DriftNotice | null {
  const { keys, services, fullRedeploy } = catalog.drift;
  const count = keys.length;
  if (count === 0) return null;
  if (!catalog.running) {
    return { text: `Start will use ${count} changed ${count === 1 ? 'setting' : 'settings'}: ${wordList(keys)}.`, offersApply: false };
  }
  const what = fullRedeploy
    ? 'Apply redeploys every service of this deployment.'
    : `Apply recreates ${wordList(services)}.`;
  const behind = count === 1 ? '1 setting is behind' : `${count} settings are behind`;
  return { text: `${behind} the running containers: ${wordList(keys)}. ${what}`, offersApply: true };
}

/**
 * Whether the running containers have no record the list can compare with,
 * which is a deployment last deployed before the manager recorded what each
 * container got. A key alone is also unknown when no running container reads
 * it, so only a list where every key is unknown says this.
 */
export function startedBeforeRecords(catalog: DeploymentSettingsCatalog): boolean {
  return catalog.running && catalog.entries.length > 0 && catalog.entries.every((entry) => entry.running === 'unknown');
}

/** Said in place of the banner when `startedBeforeRecords`, so its absence does not read as nothing to apply. */
export const UNRECORDED_NOTE =
  'The running containers were started before the manager recorded what each one got, so none of these settings can be compared with what they run. Their next deploy records it and gives them every saved value.';

/** What a save that went through says. */
export function savedText(running: boolean): string {
  return running
    ? 'Saved. The running containers keep their old values until you apply them.'
    : 'Saved. The next start uses them.';
}

/** What waits inside a folded section, so a change or a refused value in one is not lost from sight. */
export interface SectionCounts {
  unsaved: number;
  refused: number;
  behind: number;
}

/** What a key the next save or create would send is called, on its row and in its section's line. */
export function pendingChipLabel(target: SettingsEditTarget): string {
  return target === 'new-deployment' ? 'changed' : 'unsaved';
}

/** What a value the manager would refuse cannot be, for the target it is typed for. */
const REFUSED_WORDS: Readonly<Record<SettingsEditTarget, string>> = {
  deployment: 'cannot be saved',
  'new-deployment': 'cannot be used',
};

/** The line under a section's title. */
export function sectionSummary(total: number, counts: SectionCounts, target: SettingsEditTarget = 'deployment'): string {
  const parts = [total === 1 ? '1 setting' : `${total} settings`];
  if (counts.unsaved > 0) parts.push(`${counts.unsaved} ${pendingChipLabel(target)}`);
  if (counts.refused > 0) parts.push(`${counts.refused} ${REFUSED_WORDS[target]}`);
  if (counts.behind > 0) parts.push(`${counts.behind} not applied`);
  return parts.join(', ');
}

/** What the list says when a search keeps nothing. */
export function noMatchText(query: string): string {
  return `No setting matches "${query.trim()}".`;
}

/** What Apply did, from its answer. */
export function appliedText(applied: DeploymentSettingsApplied): string {
  if (applied.recreated === 'all') {
    return 'Applied. Every service of this deployment is being redeployed with the saved settings.';
  }
  if (applied.recreated.length === 0) return 'Nothing was behind, so nothing was recreated.';
  return `Applied. Recreating ${wordList(applied.recreated)} with the saved settings.`;
}

/**
 * What the footer says about the edit in progress. A value the manager would
 * refuse comes first, because that is what Save is off for.
 */
export function saveNote(changed: number, refused: readonly string[]): string {
  if (refused.length > 0) {
    const count = refused.length === 1 ? 'One value' : `${refused.length} values`;
    return `${count} cannot be saved as written: ${wordList(refused)}`;
  }
  if (changed === 0) return 'Nothing changed yet';
  return `${changed} ${changed === 1 ? 'setting' : 'settings'} changed`;
}

/** The line over the list in the new-deployment wizard, under the fold's own line saying what the list holds. */
export const NEW_DEPLOYMENT_SETTINGS_LEAD =
  "Each key shows the version's value as its default. Change only what this deployment needs, and its page can change any of them later.";

/** The line under the list in the new-deployment wizard, a value the create cannot send first. */
export function newDeploymentSettingsNote(changed: number, refused: readonly string[]): string {
  if (refused.length > 0) {
    const count = refused.length === 1 ? 'One value' : `${refused.length} values`;
    return `${count} cannot be used as written: ${wordList(refused)}`;
  }
  if (changed === 0) return "Nothing changed, so every key keeps the version's value";
  return `${changed} ${changed === 1 ? 'setting' : 'settings'} changed`;
}

/** Said of the typed keys the list for the version and services chosen now does not take. */
export function notTakenNote(keys: readonly string[]): string {
  return `Not sent, because this version does not take ${keys.length === 1 ? 'it' : 'them'} with these choices: ${wordList(keys)}.`;
}

/** Past this a description is folded to its opening words, because some samples explain a key for a page. */
export const DESCRIPTION_PREVIEW_LENGTH = 220;

/** The description as the list first shows it, cut at a word when it runs long. */
export function descriptionPreview(
  description: string,
  limit = DESCRIPTION_PREVIEW_LENGTH,
): { text: string; cut: boolean } {
  if (description.length <= limit) return { text: description, cut: false };
  const head = description.slice(0, limit + 1);
  const lastSpace = head.lastIndexOf(' ');
  const cutAt = lastSpace > 0 ? lastSpace : limit;
  return { text: `${description.slice(0, cutAt).trimEnd()}…`, cut: true };
}

function boundsText(min: number | undefined, max: number | undefined): string {
  if (min !== undefined && max !== undefined) return ` from ${min} to ${max}`;
  if (min !== undefined) return `, ${min} or more`;
  if (max !== undefined) return `, ${max} or less`;
  return '';
}

/** What a number field takes, for the line under it, or null where the control shows it already. */
export function fieldHint(field: StackSettingField | null): string | null {
  if (field?.kind === 'integer') return `A whole number${boundsText(field.min, field.max)}.`;
  if (field?.kind === 'number') return `A number${boundsText(field.min, field.max)}. Use a period for decimals.`;
  return null;
}

export interface SaveRefusal {
  message: string;
  /** Whether the list is read again, which a save that lost a race needs before anything else can be saved. */
  reload: boolean;
}

const SAVE_RACE_LOST =
  'These settings changed elsewhere after this page read them, so nothing was saved. The page has read them again. Make your change again.';

/** What a refused save says, from the manager's own error code. */
export function saveRefusalOf(code: string | null, message: string): SaveRefusal {
  if (code === 'deployment_settings_changed') return { message: SAVE_RACE_LOST, reload: true };
  return { message, reload: false };
}

/** What a refused Apply says. The manager answers a busy deployment with its code alone. */
export function applyRefusalText(code: string | null, message: string): string {
  if (code === 'profile_busy') return 'The deployment is deploying or stopping right now. Apply once it has finished.';
  return message;
}

export interface LoadFailure {
  message: string;
  /** A version with no build yet is a state to wait out rather than a fault. */
  severity: 'info' | 'warning';
}

/** Why the list is not on screen. */
export function loadFailureOf(code: string | null, message: string): LoadFailure {
  if (code === 'settings_not_ready') return { message, severity: 'info' };
  return { message: `Could not read the settings. ${message}`, severity: 'warning' };
}
