/**
 * One deployment's stack settings as its page reads and edits them.
 *
 * Every key the deployment's version declares is editable per deployment, with
 * the version's value as the default. A few keys are decided
 * by a control of their own instead, and the page shows those with their value
 * and points at that control. The page also says how many settings the
 * running containers are behind on, and offers to apply them. The engine
 * settings are in the same list, one list of settings per deployment, though
 * they are stored apart.
 */
import type { EngineDefaultSource } from './engineDefaults.js';
import type { EngineName } from './engines.js';

/**
 * Why the operator does not set a key here. Mostly the control that decides
 * it: typing over one of these would break what the manager keeps track of,
 * the port slots, the node pool, the stamp a deployment pays with. The last
 * three are engine settings the deployment does not read at all, where
 * nothing decides the key and the reason is who would read it.
 */
export type SettingOwner =
  /** Which services the deployment runs, and with them its engine. */
  | 'components'
  | 'stamp'
  | 'node-pool'
  | 'chain-endpoint'
  /** Whether the deployment's gateway runs on the chain. */
  | 'node-mode'
  | 'bee-url'
  | 'srt-passphrase'
  /** The key the deployment signs its feed with. */
  | 'feed-key'
  | 'feed-owner'
  | 'feed-topic'
  | 'engine-config'
  /** The engine settings of a deployment not created yet: the new-deployment wizard asks for the segment length in a field of its own, and its page sets the rest. */
  | 'engine-settings'
  /** The web2 admin link of a deployment not created yet, which the new-deployment wizard asks for in a group of its own. */
  | 'admin-link'
  | 'port-slot'
  | 'data-dir'
  /** A rung setting on a deployment that does not encode the ABR ladder. */
  | 'abr-only'
  /** An SRS setting on a deployment that runs no SRS. */
  | 'srs-only'
  /** An OvenMediaEngine setting on a deployment that runs no OvenMediaEngine. */
  | 'ome-only';

/** The owners that stand for a key the deployment does not read, rather than for a control that decides it. */
export const NOT_READ_OWNERS: readonly SettingOwner[] = ['abr-only', 'srs-only', 'ome-only'];

/** Whether the owner says the deployment does not read the key, which calls for different words than a control. */
export function isNotReadOwner(owner: SettingOwner): boolean {
  return NOT_READ_OWNERS.includes(owner);
}

/** Where the value the deployment's next deploy writes for a key comes from. */
export type DeploymentSettingSource =
  /** Stored for this deployment. */
  | 'deployment'
  /**
   * Set by the version's build, in its base or its engine env file. For an
   * engine setting, also what the version's engine falls back to when the
   * host sets nothing.
   */
  | 'version'
  /** The manager's own default for an engine setting, as SRT latency's 2000 is, which every version is given. */
  | 'manager-default'
  /** Decided by one of the deployment's own controls. */
  | 'manager'
  /** Generated by the manager for this deployment. */
  | 'generated'
  /** Set by nothing, so the stack's own default applies. */
  | 'unset';

/** Whether the running containers that read a key were started with the value the next deploy writes. */
export type SettingRunningState =
  | 'same'
  | 'differs'
  /** No container that reads it has a record that can tell, which a deploy before this feature leaves. */
  | 'unknown'
  /** The deployment is stopped, or is deploying, stopping or being removed, so no container is compared. */
  | 'not-running';

/** A `url` is an http or https address with a host, and no user name, password or # part. */
export type StackSettingKind = 'text' | 'integer' | 'number' | 'choice' | 'boolean' | 'url';

/** What the page knows about a value's shape, beyond the rules every env value answers to. */
export interface StackSettingField {
  kind: StackSettingKind;
  /** For a choice, every value the stack accepts. */
  choices?: readonly string[];
  min?: number;
  max?: number;
  /** For a text, the fewest characters a value that is not empty may have. */
  minLength?: number;
}

/** One key of a deployment's settings. */
export interface DeploymentSettingEntry {
  key: string;
  /** The title of the sample's section the key sits in, or an empty string. */
  section: string;
  /** The sample's comment block above the key. */
  description: string;
  /**
   * Whether the version's samples declare the key, or for an engine setting
   * the deployment reads, whether its engine does. A key neither declares is
   * listed only because the deployment still stores it.
   */
  declared: boolean;
  /** Masked by the page, and never answered in clear. */
  secret: boolean;
  /** What the version's sample assigns, a commented-out example included, or null. */
  sampleValue: string | null;
  /** Whether the version's build sets the key, which an engine setting the deployment reads always has a default for. */
  versionSet: boolean;
  /**
   * What the version's build sets, or null when it sets nothing or the key is
   * a secret. For an engine setting the deployment reads, what an unset key
   * falls back to on the deployment's host, which `engineSetting` says the
   * origin of.
   */
  versionValue: string | null;
  /** Whether this deployment stores a value of its own for the key. */
  stored: boolean;
  /** That value, or null when nothing is stored or the key is a secret. */
  storedValue: string | null;
  /**
   * What the next deploy writes, or null for a secret and for a key nothing
   * sets. A chain endpoint is answered as its host alone, because the rest can
   * carry a provider's key.
   */
  value: string | null;
  source: DeploymentSettingSource;
  /** The control that decides the key when the operator does not, or null when the operator does. */
  owner: SettingOwner | null;
  /** What the page knows about the value's shape, or null when it knows nothing beyond text. */
  field: StackSettingField | null;
  /**
   * The services whose containers read the key, from the version's compose
   * files, or null when no container's block names it. A change to such a key
   * reaches the deploy scripts alone, so applying it is a full redeploy.
   */
  services: string[] | null;
  running: SettingRunningState;
  /**
   * For an engine setting the deployment reads, what the page shows beside its
   * field, and null for every other key. The field itself, its label, unit,
   * help, kind, bounds and choices, is common's, found by the key.
   */
  engineSetting: EngineSettingFacts | null;
}

/** What a deployment's list knows of one of its own engine settings beyond the field list in common. */
export interface EngineSettingFacts {
  /** Where the default a reset goes back to comes from: the stack's own, the host's base env, or the manager's own. */
  defaultSource: EngineDefaultSource;
  /**
   * The config the engine runs no longer reads the key: the deployment's own
   * config file dropped it, or the version's template never takes it. A value
   * stored for it does nothing until the config reads it again.
   */
  notInConfig: boolean;
}

/** What the running containers are behind on. */
export interface DeploymentSettingsDrift {
  /** The keys whose next value differs from what a running container that reads them got. */
  keys: string[];
  /** The services Apply recreates. */
  services: string[];
  /** Whether a differing key reaches no container, so Apply redeploys everything. */
  fullRedeploy: boolean;
}

/** What `GET /profiles/:name/settings` answers. */
export interface DeploymentSettingsCatalog {
  /** The deployment the answer belongs to. A save names it, so a deployment recreated under the same name refuses it. */
  instanceId: string;
  /** The revision of the stored values. A save names it and is refused once another save moved it. */
  revision: number;
  /** The build of the version the next deploy uses, whose files the values and descriptions come from. */
  buildId: string | null;
  /**
   * In the sample's order, root sample first, then the engine's, then the
   * engine settings the deployment reads that neither declares, then stored
   * keys the version no longer declares.
   */
  entries: DeploymentSettingEntry[];
  drift: DeploymentSettingsDrift;
  /** Whether containers run: Apply means nothing to a stopped deployment, whose Start uses the values anyway. */
  running: boolean;
  /** The media server the deployment runs, whose settings the list lets the operator set, or null for one that runs none. */
  engine: EngineName | null;
  /** Whether the deployment encodes the ABR ladder, so the rung settings are its own. */
  abr: boolean;
  /**
   * Why the next deploy would refuse the engine settings the deployment
   * stores, in the words it refuses them with, or null. A change to the host's
   * defaults can bring this about under values it took when they were saved.
   * While it stands Apply is refused with it, a save that names an engine
   * setting has to leave them whole, and a save of other keys still lands.
   */
  engineSettingsProblem: string | null;
}

/**
 * What `GET /versions/:id/settings-catalog` answers: every key a deployment
 * that does not exist yet would start with on that version, for the wizard
 * that creates it. Nothing is stored, recorded or running, so a key's value is
 * the version's, one of the deployment's own controls decides it at the first
 * deploy, or nothing sets it.
 */
export interface NewDeploymentSettingsCatalog {
  versionId: number;
  /** The build of the version whose files the keys, values and descriptions come from. */
  buildId: string | null;
  /** In the sample's order, root sample first, then the engine's. */
  entries: DeploymentSettingEntry[];
}

/**
 * One key a new deployment is created with, in `stack_settings` of `POST
 * /profiles` and `POST /groups`. Nothing is stored yet, so there is nothing to
 * go back to and a value is always text.
 */
export interface NewDeploymentSetting {
  key: string;
  value: string;
}

/** One key of a save: a value to store, or null to go back to what the version sets. */
export interface DeploymentSettingEdit {
  key: string;
  value: string | null;
}

/** What `PUT /profiles/:name/settings` takes. Keys it leaves out keep what they have. */
export interface DeploymentSettingsSave {
  expectedInstanceId: string;
  expectedRevision: number;
  entries: DeploymentSettingEdit[];
}

/**
 * Each control as a sentence names it, for a refusal and for the page's
 * pointer to it, and for a key the deployment does not read, the reason, as
 * the clause a sentence ends on.
 */
export const SETTING_OWNER_LABELS: Readonly<Record<SettingOwner, string>> = {
  components: 'the services the deployment runs',
  stamp: "the deployment's postage stamp",
  'node-pool': "the deployment's node pool",
  'chain-endpoint': "the deployment's chain endpoint",
  'node-mode': "the gateway's node mode",
  'bee-url': "the deployment's Bee URL",
  'srt-passphrase': "the deployment's SRT passphrase",
  'feed-key': "the deployment's feed key",
  'feed-owner': "the deployment's feed owner",
  'feed-topic': "the deployment's feed topic",
  'engine-config': "the engine's own config file",
  'engine-settings': 'the engine settings',
  'admin-link': 'the Web2 admin group of this step',
  'port-slot': "the deployment's port slot",
  'data-dir': 'the manager, which keeps this deployment\'s data on its own host',
  'abr-only': 'only a deployment that encodes the ABR ladder reads it',
  'srs-only': 'only a deployment that runs SRS reads it',
  'ome-only': 'only a deployment that runs OvenMediaEngine reads it',
};

/** What a save answers. */
export interface DeploymentSettingsSaved {
  revision: number;
}

/** What `POST /profiles/:name/settings/apply` answers: the services it recreates, or all of them. */
export interface DeploymentSettingsApplied {
  recreated: string[] | 'all';
}
