/**
 * One deployment's stack settings as its page reads and edits them.
 *
 * Every key the deployment's version declares is editable per deployment, with
 * the version's value as the default (the owner, 2026-09-25). A few keys are decided
 * by a control of their own instead, and the page shows those with their value
 * and points at that control. The page also says how many settings the
 * running containers are behind on, and offers to apply them, which the owner
 * okayed the same day.
 */

/**
 * The control that decides a key when the operator does not. Typing over one
 * of these would break what the manager keeps track of: the port slots, the
 * node pool, the stamp a deployment pays with.
 */
export type SettingOwner =
  /** Which services the deployment runs, and with them its engine. */
  | 'components'
  | 'stamp'
  | 'node-pool'
  | 'chain-endpoint'
  /** Whether the deployment's gateway runs on the chain. */
  | 'node-mode'
  | 'bee-url'
  | 'srt-passphrase'
  /** The key the deployment signs its feed with. */
  | 'feed-key'
  | 'feed-owner'
  | 'feed-topic'
  | 'engine-config'
  | 'engine-settings'
  | 'port-slot'
  | 'data-dir';

/** Where the value the deployment's next deploy writes for a key comes from. */
export type DeploymentSettingSource =
  /** Stored for this deployment. */
  | 'deployment'
  /** Set by the version's build, in its base or its engine env file. */
  | 'version'
  /** Decided by one of the deployment's own controls. */
  | 'manager'
  /** Generated by the manager for this deployment. */
  | 'generated'
  /** Set by nothing, so the stack's own default applies. */
  | 'unset';

/** Whether the running containers that read a key were started with the value the next deploy writes. */
export type SettingRunningState =
  | 'same'
  | 'differs'
  /** No container that reads it has a record that can tell, which a deploy before this feature leaves. */
  | 'unknown'
  /** The deployment is stopped, so nothing runs with any value. */
  | 'not-running';

export type StackSettingKind = 'text' | 'integer' | 'number' | 'choice' | 'boolean';

/** What the page knows about a value's shape, beyond the rules every env value answers to. */
export interface StackSettingField {
  kind: StackSettingKind;
  /** For a choice, every value the stack accepts. */
  choices?: readonly string[];
  min?: number;
  max?: number;
}

/** One key of a deployment's settings. */
export interface DeploymentSettingEntry {
  key: string;
  /** The title of the sample's section the key sits in, or an empty string. */
  section: string;
  /** The sample's comment block above the key. */
  description: string;
  /** Masked by the page, and never answered in clear. */
  secret: boolean;
  /** What the version's sample assigns, a commented-out example included, or null. */
  sampleValue: string | null;
  /** Whether the version's build sets the key. */
  versionSet: boolean;
  /** What the version's build sets, or null when it sets nothing or the key is a secret. */
  versionValue: string | null;
  /** Whether this deployment stores a value of its own for the key. */
  stored: boolean;
  /** That value, or null when nothing is stored or the key is a secret. */
  storedValue: string | null;
  /**
   * What the next deploy writes, or null for a secret and for a key nothing
   * sets. A chain endpoint is answered as its host alone, because the rest can
   * carry a provider's key.
   */
  value: string | null;
  source: DeploymentSettingSource;
  /** The control that decides the key when the operator does not, or null when the operator does. */
  owner: SettingOwner | null;
  /** What the page knows about the value's shape, or null when it knows nothing beyond text. */
  field: StackSettingField | null;
  /**
   * The services whose containers read the key, from the version's compose
   * files, or null when no container's block names it. A change to such a key
   * reaches the deploy scripts alone, so applying it is a full redeploy.
   */
  services: string[] | null;
  running: SettingRunningState;
}

/** What the running containers are behind on. */
export interface DeploymentSettingsDrift {
  /** The keys whose next value differs from what a running container that reads them got. */
  keys: string[];
  /** The services Apply recreates. */
  services: string[];
  /** Whether a differing key reaches no container, so Apply redeploys everything. */
  fullRedeploy: boolean;
}

/** What `GET /profiles/:name/settings` answers. */
export interface DeploymentSettingsCatalog {
  /** The deployment the answer belongs to. A save names it, so a deployment recreated under the same name refuses it. */
  instanceId: string;
  /** The revision of the stored values. A save names it and is refused once another save moved it. */
  revision: number;
  /** The build of the version the next deploy uses, whose files the values and descriptions come from. */
  buildId: string | null;
  /** In the sample's order, root sample first, then the engine's, then stored keys the version no longer declares. */
  entries: DeploymentSettingEntry[];
  drift: DeploymentSettingsDrift;
  /** Whether containers run: Apply means nothing to a stopped deployment, whose Start uses the values anyway. */
  running: boolean;
}

/** What `PUT /profiles/:name/settings` takes. */
export interface DeploymentSettingsSave {
  expectedInstanceId: string;
  expectedRevision: number;
  /** Per key, a value to store, or null to go back to what the version sets. Keys left out keep what they have. */
  values: Record<string, string | null>;
}

/** What a save answers. */
export interface DeploymentSettingsSaved {
  revision: number;
}

/** What `POST /profiles/:name/settings/apply` answers: the services it recreates, or all of them. */
export interface DeploymentSettingsApplied {
  recreated: string[] | 'all';
}
